server:
    port: 8080

security:
  basic:
    enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          daeun:
            client-id: sally_first_app1600150912610
            client-secret: 740c6955e09d51423f21cda8aa3d6b0bd8a113aaa546e9ae9486b600aabdaaa6
            authorization-grant-type: authorization_code
            redirect-uri-template: http://localhost:8080/login/oauth2/code/daeun
        provider:
          daeun:
            authorization-uri: http://localhost:8082/auth/oauth/authorize
            token-uri: http://localhost:8082/auth/oauth/token
            user-info-uri: http://localhost:8082/auth/user/info
            user-name-attribute: id
