server:
    port: 8080

security:
  basic:
    enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          daeun:
            client-id: chocochoco1600150947626
            client-secret: 493dab9a17f55be6d34a1f8b091295e26f1687adb06190b6b5d3d405f11cba71
            authorization-grant-type: authorization_code
            redirect-uri-template: http://localhost:8080/login/oauth2/code/daeun
        provider:
          daeun:
            authorization-uri: http://localhost:8082/auth/oauth/authorize
            token-uri: http://localhost:8082/auth/oauth/token
            user-info-uri: http://localhost:8082/auth/user/info
            user-name-attribute: id
