server:
    port: 8082
    servlet:
      context-path: /client

security:
  basic:
    enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          daeun:
            client-id: y'sappaswell1599714760301
            client-secret: 48e8779c23458521a902a0285edbb53419570c83b5be8e2736b8b95619203c2a
            authorization-grant-type: authorization_code
            redirect-uri-template: http://localhost:8082/client/login/oauth2/code/daeun
        provider:
          daeun:
            authorization-uri: http://localhost:8080/auth/oauth/authorize
            token-uri: http://localhost:8080/auth/oauth/token
            user-info-uri: http://localhost:8080/auth/user/info
            user-name-attribute: id
