server:
    port: 8082
    servlet:
      context-path: /api

security:
  basic:
    enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          daeun:
            client-id: my_first_app1599720866673
            client-secret: dc1a9e7f12adc94bff1a1ddc657d4a31849d3697ffb17528059a68f720a66eac
            authorization-grant-type: authorization_code
            redirect-uri-template: http://localhost:8082/api/login/oauth2/code/daeun
        provider:
          daeun:
            authorization-uri: http://localhost:8080/auth/oauth/authorize
            token-uri: http://localhost:8080/auth/oauth/token
            user-info-uri: http://localhost:8080/auth/user/info
            user-name-attribute: id
